module.exports = {
	extends: ['@commitlint/config-conventional'],
	rules: {
		'body-leading-blank': [2, 'always'],
		'footer-leading-blank': [2, 'always'],
		'scope-enum': [
			2,
			'always',
			[
				'accordion',
				'alert',
				'alert-dialog',
				'aspect-ratio',
				'attachment',
				'autocomplete',
				'avatar',
				'badge',
				'breadcrumb',
				'bubble',
				'button',
				'button-group',
				'calendar',
				'card',
				'carousel',
				'checkbox',
				'cli',
				'collapsible',
				'combobox',
				'command',
				'context-menu',
				'data-table',
				'date-picker',
				'dialog',
				'drawer',
				'dropdown-menu',
				'empty',
				'field',
				'hover-card',
				'input',
				'input-group',
				'input-otp',
				'item',
				'kbd',
				'label',
				'marker',
				'mcp',
				'menubar',
				'message',
				'native-select',
				'navigation-menu',
				'number-field',
				'pagination',
				'popover',
				'progress',
				'radio-group',
				'resizable',
				'scroll-area',
				'select',
				'separator',
				'sheet',
				'sidebar',
				'skeleton',
				'slider',
				'sonner',
				'spinner',
				'stepper',
				'switch',
				'table',
				'tabs',
				'textarea',
				'toggle',
				'toggle-group',
				'tooltip',
				'trpc',
				'typography',
				'nx',
				'repo',
				// semantic-release stamps the release commit as `chore(release): <version>`.
				'release',
			],
		],
		'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
	},
};
